# Generated by Django 4.0.5 on 2022-06-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rezume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('file', models.FileField(max_length=255, upload_to='rezume_files/%Y/%m/%d', verbose_name='Объект документа')),
                ('full_name', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта/Логин')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('education', models.TextField(default='', verbose_name='Образование')),
                ('experience', models.TextField(default='', verbose_name='Опыт работы')),
                ('skills', models.TextField(default='', verbose_name='Проффесиональные навыки')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ('-datetime_created',),
            },
        ),
    ]
