# Generated by Django 4.0.4 on 2022-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(default='', verbose_name='Опыт работы'),
        ),
    ]
