# Generated by Django 4.0.5 on 2022-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0003_alter_resume_file_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='rezume_files/%Y/%m/%d', verbose_name='Объект документа')),
            ],
        ),
    ]
