# Generated by Django 4.0.5 on 2022-06-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezume', '0004_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
